// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNNkBFTroVp1dOKFhQvni27eQv2XeRjrs',
    appId: '1:1007756831640:web:670fd4e36aee94bf2059ed',
    messagingSenderId: '1007756831640',
    projectId: 'database-1efb9',
    authDomain: 'database-1efb9.firebaseapp.com',
    storageBucket: 'database-1efb9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_7lsAO8XjNBKVSLqRYbFERTk-qN7gsRk',
    appId: '1:1007756831640:android:4ae1eb3bdfd893ec2059ed',
    messagingSenderId: '1007756831640',
    projectId: 'database-1efb9',
    storageBucket: 'database-1efb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDefT1fJWiRwpK6404sIfq8bhGktWwIcHU',
    appId: '1:1007756831640:ios:340fc41d8a0668e32059ed',
    messagingSenderId: '1007756831640',
    projectId: 'database-1efb9',
    storageBucket: 'database-1efb9.appspot.com',
    iosBundleId: 'com.example.posttest6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDefT1fJWiRwpK6404sIfq8bhGktWwIcHU',
    appId: '1:1007756831640:ios:8c713badfa09f9032059ed',
    messagingSenderId: '1007756831640',
    projectId: 'database-1efb9',
    storageBucket: 'database-1efb9.appspot.com',
    iosBundleId: 'com.example.posttest6.RunnerTests',
  );
}
